server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineshop
    driverClassName: org.postgresql.Driver
    username: postgres
    password:

hibernate:
  properties:
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    dialect: org.hibernate.dialect.HSQLDialect
    showSQL: true
    formatSQL: true

cxf:
  path: /petProject
