server:
  port: 8091

spring:
  basePackage: application
  datasource:

#    jdbc-url: jdbc:postgresql://localhost:5432/onlineshop
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: root

    jdbc-url: jdbc:h2:file:./sample2;INIT=runscript from 'classpath:/OnlineShopSqlScript2.sql'
    driverClassName: org.h2.Driver
    username: sa
    password:

  liquibase:
    url: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=TRUE;
#    username: test
#    password: test
#    url: jdbc:postgresql://localhost:5432/onlineshop
#    username: postgres
#    password: root
    changeLog: classpath:/changelogs/liquibase-changeLog4.xml # файл который будет использоваться при запуске
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create # Это нужно для того, чтобы Hibernate не выполнял никаких действий по модификации схемы, т.к. теперь их будет делать Liquibase.
  h2:
    console:
      enabled: true
      path: /h2

hibernate:
  jdbc:
    lob:
      non_contextual_creation: true
  properties:
#    dialect: org.hibernate.dialect.PostgreSQL95Dialect # for java 11
    dialect: org.hibernate.dialect.H2Dialect # for java 11
    showSQL: true
    formatSQL: true

cxf:
  path: /petProject

debug: false



