server:
  port: 8091

spring:
  basePackage: application
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/onlineshop
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:/changelogs/liquibase-changeLog3.xml
hibernate:
  jdbc:
    lob:
      non_contextual_creation: true
  properties:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect # for java 11
    showSQL: true
    formatSQL: true


cxf:
  path: /petProject

debug: false
